name: Tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'README.md.erb'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'README.md.erb'

jobs:
  unit_tests:
    name: Unit Tests
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          # Bundler 1.x not working on CI
          # - "2.2"
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
        allow_failures:
          - false
        include:
          - ruby: ruby-head
            allow_failures: true
    env:
      ALLOW_FAILURES: "${{ matrix.allow_failures }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rspec || $ALLOW_FAILURES
